### ISSUE TITLE
TODO #1:

### ISSUE THREAD

**Issue by leonardovlibido** [MATF-RG16/RG16-093-delicate-descent#1]
## Things to implement in the upcoming week (or day):

- [x] Add random generating obstacles (mattresses).
- [x] Add collision detection between player and mattress.
- [x] Improve guy_falling_animation: add leg movement, add body fidgeting.
- [x] Improve guy_on_impact animation for mattresses (e.g. position the guy in the center, bounce effect)
- [ ] Improve guy_on_impact animation for falling on the floor (e.g. add some blood, lose some limbs).
- [ ] Add Endgame screen
- [x] Write a descent README.mk
